
listSites <- function(dataset){
  
  sites <- c(
    "Afjord fjellstyre nord", 
    "Afjord fjellstyre sør", 
    "Anarjohka", 
    "Arefjell", 
    "Berghøgda", 
    "Blåsenborg", 
    "Byvann", 
    "Båttjønndalen", 
    "Bæråsen", 
    "Cunucearru", 
    "Dalsia", 
    "Damtjønnflonan", 
    "Daningen", 
    "Dovrefjell", 
    "Dunfjell", 
    "Dyngjane", 
    "Eidfjord Fjellstyre", 
    "Elvasshei", 
    "Finnvellen", 
    "Fjeset-Nekå", 
    "Fron Fjellstyre", 
    "Gausdal kontr.", 
    "Gausdal refugie.", 
    "Geadgejavri", 
    "Gløtvola / Vilt 3", 
    "Grautheller", 
    "Grimsdalen", 
    "Grøndalshøgda", 
    "Gåvålia", 
    "Harodalen", 
    "Hatter", 
    "Haustreisdalen", 
    "Hein/Ø. Numedal Fjellstyre", 
    "Hele strekket", 
    "Hjelmsøy", 
    "Holmevann", 
    "Hyttehei", 
    "Ifjord-Lebesby", 
    "Ifjord-Tana", 
    "Indre Finnvellen", 
    "Jarfjord", 
    "Kaldvatn", 
    "Karasjok Aitevarri", 
    "Karasjok Iskuras", 
    "Kjensvatn", 
    "Kjæs", 
    "Klubbfjellet", 
    "Komagdalen", 
    "Kongsvoll", 
    "Krutfjellet", 
    "Kvikne ABC", 
    "Kvikne D", 
    "Kvikne E", 
    "Kviknebrona", 
    "Kvitvola / Vilt 2", 
    "Laksfjordvidda/Kunes", 
    "Leirpollen", 
    "Lierne Fjellst. Vest", 
    "Lierne Fjellst. øst", 
    "Lillerøåsen / Vilt 1", 
    "Lordalen", 
    "Maskevarre", 
    "Maze", 
    "Middagskneppen", 
    "Namsskogan Fjellstyre", 
    "Nattvann", 
    "Neiden", 
    "Nordre Salten", 
    "Nyborgmoen/Kroken", 
    "Os Fjellstyre", 
    "Osen Fjellstyre", 
    "Regionfelt Østlandet", 
    "Ringebu Fjellstyre", 
    "Risknappan", 
    "Rolvsøy", 
    "Røyrvik Fjellstyre", 
    "Saltfjellet", 
    "Savngovann", 
    "Selbu Fjellstyre", 
    "Sennalandet", 
    "Slagfjellet", 
    "Slettfjellet", 
    "Snåsa Fjellstyre", 
    "Soknedal Søndre", 
    "Sollia", 
    "Sone 1 / Vilt 3", 
    "Sone 3 / Vilt 3", 
    "Spielgajavrrit", 
    "Stalluvarre", 
    "Statsallmenningene i Namdalseid", 
    "Statskog Røros", 
    "Statskog og Klinga utm.", 
    "Steinkj. Kommuneskog", 
    "Steinkjer Fjellstyre", 
    "Stilla – Joatka", 
    "Stjørdal Fjellstyre", 
    "Storakersvatnet", 
    "Sulitjelma", 
    "Suossjavri", 
    "Sørøya", 
    "Tanadalen", 
    "Taumevann", 
    "Tågå", 
    "Valnesfjord", 
    "Vestre Slidre Fjellstyre", 
    "Viltstellområde 3 Skogsfugl", 
    "Virvassdalen", 
    "Ytre Salten", 
    "Åfjord utmarkslag", 
    "Østfjellet / Vilt 2", 
    "Øystre Slidre 1", 
    "Øystre Slidre 2", 
    "Øyvasskilen"
  )
  return(sites)
}

